version: "3"

services:
    web:
        image: nginx
        restart: unless-stopped
        volumes:
            - ../public:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
